[project]
name = "platynui-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "robotframework>=7.4.1",
    "robotframework-jsonrpcremote>=0.1.0",
    "robotframework-jsonrpcremote-protocol>=0.1.0",
]
