[project]
name = "platynui-workshop"
version = "0.1.0"
description = "Explore robotframework-platynui, a new cross-platform library for desktop UI automation with Robot Framework."
requires-python = ">=3.11,<3.14"
dependencies = [
    "robotframework>=7.4.1",
    "robotframework-platynui>=0.9.2",
]
